server:
  port: 8080
  servlet:
    context-path: /
spring:
  devtools:
    restart:
      enabled: true #开启热部署
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baojia?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: qaz123456
    hikari:
      minimum-idle: 5 #最小空闲连接数
      maximum-pool-size: 15 #最大连接数，默认10
      auto-commit: true #自动提交，默认true
      idle-timeout: 30000 #空闲连接存活最大时间，默认600000(10分钟)
      pool-name: BaojiaHikariCP #连接池名称
      max-lifetime: 1800000 #最长生命周期，默认1800000(30分钟)，0表示无限生命周期
      connection-timeout: 30000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #连接测试查询
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.108.11
    port: 6379
    database: 0
    timeout: 2000ms #连接超时时间
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间(负值表示没有限制)
        min-idle: 0 #连接池最小空闲连接
        max-idle: 8 #连接池最大空闲连接
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xlhj.baojia.entity
logging:
  config: classpath:logback-spring.xml
  level:
    com.xlhj.baojia: debug

jwt:
  header: Authorization
  tokenPrefix: Bearer #token前缀
  tokenSecret: qazxswedcvfrtgbnhyujmkiolp #密钥
  tokenExpired: 900 #token过期时间(秒)